[phases.setup]
nixPkgs = ["python311", "ffmpeg", "mesa", "glib", "xorg.libX11", "xorg.libXext", "xorg.libxcb", "xorg.libXrender"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libxcb1", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "bash start.sh"
